### ISSUE TITLE
other code edit for you to see

### ISSUE THREAD

**Issue by wuqinglaoxingxing** [yelloxing/Web-Studio-Code#3]
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgBQCUwAOlPkQM4Amth9hANoQx-VTQG6EAnIvgC8+CiEISA3FQC+IADQgIAB1zRayUIIEQA7gAVBCLSjb7CATy3KARgMJgA1nBgBlVU5xQA5shgBdDhlAAsYAFtWAHVQnHhaLzA4d1N4nF54q2RwWlsQH1o4ARhDR18IwmRUNiLlACtaAA8AIUcXN3dCCLgAGR84atqQkEam9x9fVjgARXQIeCHWOpAvASKBHLtCOzhWJVWBHxhonHoYUOQADgAGZVU9IujHVRyHuA3eQeUAR3n4MpqMySWgAWigcDg9ChBwEcD+ODhZUIFSqSBqyxGRQiOACQSxk2mcwWg3Rw2UMB2p3OlyQACYKY4cKxJgBhCARSo5D4AVgO6CKABUdmYMSteMEAJJQaGwdxgI7qACCMvcMCs0yWRTkciAA

**Comment by yelloxing** [comment]
OK

**Comment by yelloxing** [comment]
由于issue2问题已经找到并修复，故关闭！
